# Generated by Django 4.2.16 on 2024-09-16 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('ticker', models.CharField(default='', max_length=25)),
                ('legibility', models.CharField(default='', max_length=5)),
                ('difficulty', models.CharField(default='', max_length=7)),
                ('startprice', models.FloatField()),
                ('img', models.ImageField(blank=True, default='airdropLogo.jpg', null=True, upload_to='coin_images/')),
                ('contract_add', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers', models.IntegerField()),
                ('integrity_score', models.FloatField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('color', models.JSONField(blank=True, default=dict, null=True)),
                ('category', models.CharField(choices=[('DeFi', 'DeFi'), ('NFT', 'NFT'), ('Gaming', 'Gaming'), ('Others', 'Others')], default='Others', max_length=50)),
                ('token_type', models.CharField(choices=[('ERC-20', 'ERC-20'), ('BEP-20', 'BEP-20'), ('SPL', 'SPL'), ('Others', 'Others')], default='Others', max_length=50)),
                ('creator', models.CharField(default=' ', max_length=255)),
                ('partners', models.JSONField(blank=True, default=dict, null=True)),
                ('timeline', models.JSONField(blank=True, default=dict, null=True)),
                ('token_allocation', models.JSONField(blank=True, default=dict, null=True)),
                ('vesting_schedule', models.JSONField(blank=True, default=dict, null=True)),
                ('lockup_periods', models.JSONField(blank=True, default=dict, null=True)),
                ('token_utility', models.JSONField(blank=True, default=dict, null=True)),
                ('community_size', models.IntegerField(blank=True, null=True)),
                ('social_media_metrics', models.JSONField(blank=True, default=dict, null=True)),
                ('website_traffic', models.JSONField(blank=True, default=dict, null=True)),
                ('faqs', models.JSONField(blank=True, default=dict, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('tokenomics', models.JSONField(blank=True, default=dict, null=True)),
                ('roadmap', models.JSONField(blank=True, default=dict, null=True)),
                ('team_info', models.JSONField(blank=True, default=dict, null=True)),
                ('advisors', models.JSONField(blank=True, default=dict, null=True)),
                ('investors', models.JSONField(blank=True, default=dict, null=True)),
                ('airdrop_history', models.JSONField(blank=True, default=dict, null=True)),
                ('testimonials', models.JSONField(blank=True, default=dict, null=True)),
                ('ratings_reviews', models.JSONField(blank=True, default=dict, null=True)),
                ('audit_reports', models.JSONField(blank=True, default=dict, null=True)),
                ('token_listing', models.JSONField(blank=True, default=dict, null=True)),
                ('localization', models.JSONField(blank=True, default=dict, null=True)),
                ('user_guides', models.JSONField(blank=True, default=dict, null=True)),
                ('updates_news', models.JSONField(blank=True, default=dict, null=True)),
                ('compliance_info', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=50)),
                ('airdrop_type', models.CharField(choices=[('Bounty', 'Bounty'), ('Giveaway', 'Giveaway'), ('Fork', 'Fork'), ('Others', 'Others')], default='Others', max_length=50)),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict, null=True)),
                ('claim_distribution', models.JSONField(blank=True, default=dict, null=True)),
                ('user_interactions', models.JSONField(blank=True, default=dict, null=True)),
                ('budget_funding', models.JSONField(blank=True, default=dict, null=True)),
                ('token_price_market', models.JSONField(blank=True, default=dict, null=True)),
                ('security_measures', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, default='airdropLogo.jpg', null=True, upload_to='coin_images/')),
                ('description', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('tracked_airdrops', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('airdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airdrop')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('airdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airdrop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scopeuser')),
            ],
        ),
        migrations.CreateModel(
            name='FollowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_url', models.CharField(max_length=255)),
                ('follower_num', models.IntegerField()),
                ('followed_airdrop', models.ManyToManyField(to='core.airdrop')),
            ],
        ),
        migrations.AddField(
            model_name='airdrop',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blockchain'),
        ),
        migrations.AddField(
            model_name='airdrop',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.event'),
        ),
    ]
