# Generated by Django 4.2.16 on 2024-09-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdrop',
            name='img',
            field=models.ImageField(blank=True, default='/storage/emulated/0/airdrop_8290002-1.png', null=True, upload_to='coin_images/'),
        ),
    ]
